import Head from "next/head";
import DataTable from "./DataTable";
import Navbar from "./Navbar";

const Layout = ({ products }) => {
  return (
    <>
      <Head>
        <title>Province of BC - Web Applications Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <DataTable products={products} />
    </>
  );
};

export default Layout;
