import Head from "next/head";
import AddModal from "./AddModal";
import EditModal from "./EditModal";
import DataTable from "./DataTable";
import Navbar from "./Navbar";
import DeleteModal from "./DeleteModal";
import styles from "../styles/Home.module.css";
import Search from "./Search";

const Layout = ({
  dataForDisplay,
  selectedDevelopers,
  setSelectedDevelopers,
  formConditioning,
  setFormConditioning,
  form,
  setForm,
  isOpenAdd,
  setIsOpenAdd,
  isOpen, //                      <-----  list of props from index.tsx
  setIsOpen,
  isOpenDelete,
  setIsOpenDelete,
  isOpenSearch,
  setIsOpenSearch,
  deleteId,
  setDeleteId,
  editData,
  setEditData,
  selectedEditDevelopers,
  setSelectedEditDevelopers,
  handleEditClick,
  handleDeleteClick,
  deleteDeveloper,
  handleSearchInput,
  searchQuery,
  setSearchQuery,
}: any) => {
  return (
    <>
      <Head>
        <title>Province of BC - Web Applications Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.page}>
        <AddModal
          formConditioning={formConditioning}
          setFormConditioning={setFormConditioning}
          isOpenAdd={isOpenAdd}
          setIsOpenAdd={setIsOpenAdd}
          selectedDevelopers={selectedDevelopers}
          setSelectedDevelopers={setSelectedDevelopers}
          form={form}
          setForm={setForm}
          deleteDeveloper={deleteDeveloper}
        />
        <EditModal
          formConditioning={formConditioning}
          setFormConditioning={setFormConditioning}
          isOpen={isOpen}
          setIsOpen={setIsOpen}
          editData={editData}
          setEditData={setEditData}
          selectedEditDevelopers={selectedEditDevelopers}
          setSelectedEditDevelopers={setSelectedEditDevelopers}
          deleteDeveloper={deleteDeveloper}
        />
        <DeleteModal
          isOpenDelete={isOpenDelete}
          setIsOpenDelete={setIsOpenDelete}
          deleteId={deleteId}
          setDeleteId={setDeleteId}
        />

        <h1>IMB Database</h1>
        <div className={styles.align_right}>
          <div className={styles.button} onClick={() => setIsOpenAdd(true)}> {/* trigers isOpenAdd to display AddModal.tsx */}
            <p>Add New</p>
          </div>
        </div>

        <DataTable
          dataForDisplay={dataForDisplay}
          handleEditClick={handleEditClick}
          handleDeleteClick={handleDeleteClick}
          isOpenAdd={isOpenAdd}
        />

        <Search
          isOpenSearch={isOpenSearch}
          setIsOpenSearch={setIsOpenSearch}
          handleSearchInput={handleSearchInput}
          searchQuery={searchQuery}
          setSearchQuery={setSearchQuery}
        />
      </div>
    </>
  );
};

export default Layout;
