import Head from "next/head";
import AddModal from "./AddModal";
import EditModal from "./EditModal";
import DataTable from "./DataTable";
import Navbar from "./Navbar";

const Layout = ({
  products,
  selectedDevelopers,
  setSelectedDevelopers,
  formConditioning,
  setFormConditioning,
  form,
  setForm,
  isOpenAdd,
  setIsOpenAdd,
  isOpen,
  setIsOpen,
  editData,
  setEditData,
  selectedEditDevelopers,
  setSelectedEditDevelopers,
  handleEditClick,
  deleteDeveloper,
}: any) => {
  return (
    <>
      <Head>
        <title>Province of BC - Web Applications Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <AddModal
        formConditioning={formConditioning}
        setFormConditioning={setFormConditioning}
        isOpenAdd={isOpenAdd}
        setIsOpenAdd={setIsOpenAdd}
        products={products}
        selectedDevelopers={selectedDevelopers}
        setSelectedDevelopers={setSelectedDevelopers}
        form={form}
        setForm={setForm}
        deleteDeveloper={deleteDeveloper}
      />
      <EditModal
        formConditioning={formConditioning}
        setFormConditioning={setFormConditioning}
        isOpen={isOpen}
        setIsOpen={setIsOpen}
        editData={editData}
        setEditData={setEditData}
        selectedEditDevelopers={selectedEditDevelopers}
        setSelectedEditDevelopers={setSelectedEditDevelopers}
        deleteDeveloper={deleteDeveloper}
      />
      <DataTable
        products={products}
        handleEditClick={handleEditClick}
        isOpenAdd={isOpenAdd}
        setIsOpenAdd={setIsOpenAdd}
      />
    </>
  );
};

export default Layout;
